In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

Collecting numpy
  Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 8.4 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.3 MB 6.9 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 7.7 MB/s eta 0:00:02
   ----------------- ---------------------- 5.2/12.3 MB 7.4 MB/s eta 0:00:01
   ---------------------- ----------------- 6.8/12.3 MB 6.9 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.3 MB 6.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 7.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 7.0 MB/s  0:00:01
Installing collected packages: numpy
Successfully installed numpy-2.4.6
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np

In [8]:
#1D array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) #dimension of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [10]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1, 5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [15]:
arr3=np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr3.shape)

(2, 5)

In [19]:
np.arange(0, 10, 2).reshape(1, 5)

array([[0, 2, 4, 6, 8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr4=np.array([[1,2,3], [4,5,6]])
print(arr4.shape) #shape of array
print(arr4.ndim) #row dimn
print(arr4.size) #no of elements
print(arr4.dtype) #element data type
print(arr4.itemsize) #size of element

(2, 3)
2
6
int64
8

In [24]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([-1,-2,-3,-4,-5])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[0 0 0 0 0]
[ 2  4  6  8 10]
[ -1  -4  -9 -16 -25]
[-1. -1. -1. -1. -1.]

In [26]:
#universal functions
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

In [27]:
arr6=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [31]:
#statistical concepts- normalization
data = np.array([1,2,3,4,5])
mean= np.mean(data)
std_dev=np.std(data)
normalized_data = (data-mean)/std_dev
print("normalised data: ", normalized_data)

normalised data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [33]:
mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)
print(mean, std_dev, variance)

3.0 1.4142135623730951 2.0

In [37]:
data=np.array([1,2,3,4,5,6,7,])
print(data>5)

[False False False False False  True  True]

In [40]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\MachineLearning\venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\MachineLearning\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\MachineLearning\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ----------------- ---------------------- 4.2/9.8 MB 22.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 23.3 MB/s  0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

In [41]:
import pandas as pd

In [42]:
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [44]:
data={'a':1, 'b':2, 'c':3}
series_dict= pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [46]:
data=[10,20,30]
index=['a', 'b', 'c']
pd.Series(index,index=data)

10    a
20    b
30    c
dtype: str

In [47]:
data={
    'Name': ['Krish', 'John', 'Jack'],
    'Age': [25,30,45], 
    'City': ['Bangalore', 'Delhi', 'Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30      Delhi
2   Jack   45    Florida
<class 'pandas.DataFrame'>

In [48]:
np.array(df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'Delhi'],
       ['Jack', 45, 'Florida']], dtype=object)

In [50]:
df.loc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [51]:
df.iloc[0]

Name        Krish
Age            25
City    Bangalore
Name: 0, dtype: object

In [52]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [55]:
df['Salary']=[50000, 60000, 70000]
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30      Delhi   60000
2   Jack   45    Florida   70000

In [56]:
df.drop('Salary', axis=1)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30      Delhi
2   Jack   45    Florida